spring:
  application:
    name: jooqWithLiquibaseUsingMariaDB4j
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:${mariaDB4j.port}/test
    username: root
    password:
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml


mariaDB4j:
  port: 3307

